name: Main Workflow
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  # Add Publisher Job here
  build:
    uses: ./.github/workflows/build.yml
    secrets: inherit
  syntax:
    uses: ./.github/workflows/syntax.yml
    needs: build
    secrets: inherit
  scan:
    uses: ./.github/workflows/scan.yml
    needs: build
    secrets: inherit