name: Publish Artifacts

# TODO: Update this workflow to only run when 
# a tag has been created.
on:
  push:
    tags:
      - '\d+\.\d+\.\d+' # Tags like 1.0.0, 1.0.0, etc.

permissions:
  id-token: write
  contents: read

jobs:
  pypi-publish:
    name: Upload Release to PyPI
    runs-on: ubuntu-latest
    # Specifying a GitHub environment is optional, but strongly encouraged
    environment: pypi
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install build
      - name: Build package
        run: |
          python -m build
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1

