name: Security Scanning

on:
  workflow_call:

jobs:
  generate-sbom:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate SBOM with Trivy
        run: |
          docker run --rm -v $(pwd):/app aquasec/trivy:latest fs --format cyclonedx --output /app/sbom.json /app

      - name: Upload SBOM artifact
        uses: actions/upload-artifact@v2
        with:
          name: sbom
          path: sbom.json
